### ISSUE TITLE
ValueError: Attempted to map inputs that were not found in graph_def: [input:0]

### ISSUE THREAD

**Issue by rohith14** [huanzhang12/tensorflow-alexnet-model#2]
I am using the alexnet_frozen.pb and 
## Repro code

pbName = "alexnet_frozen.pb"
 with gfile.FastGFile(pbName, "rb") as f: 
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

tf.logging.info("Starting execution")
  gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.50)
  #gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.67)
  tf.reset_default_graph()
  g = tf.Graph()
  outlist = []
  with g.as_default():
    inc=tf.constant(dummy_input, dtype=tf.float32)
    dataset=tf.data.Dataset.from_tensors(inc)
    dataset=dataset.repeat()
    iterator=dataset.make_one_shot_iterator()
    next_element=iterator.get_next()
    out = tf.import_graph_def(
      graph_def=gdef,
      input_map={"input":next_element},
      return_elements=["Softmax"]
    )

## Error
Traceback (most recent call last):
  File "test_TF_TensorRT_Prediction_GPU.py", line 169, in <module>
    speed = score(gDef, batch_size, dummy_input, strRetElements, num_loops)
  File "test_TF_TensorRT_Prediction_GPU.py", line 80, in score
    return_elements=[strRetElements]
  File "/local/Anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/local/Anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 777, in import_graph_def
    % ', '.join(absent_input_keys))
ValueError: Attempted to map inputs that were not found in graph_def: [input:0]

**Comment by huanzhang12** [comment]
The input node name is "Placeholder:0"

**Comment by huanzhang12** [comment]
You can checkout the code here on how to use the frozen protobuf:

https://github.com/huanzhang12/CLEVER/blob/master/setup_imagenet.py#L146
